const pageKey = document.body.dataset.page || "retail";

const pages = {
  retail: {
    title: "We know your needs", eyebrow: "For you", lead: "All the best, always for you", hero: "assets/images/retail/hero-for-you.jpg",
    introTitle: "All the best, always for you", intro: ["Every day we give you energy to act. Across Central Europe, ORLEN combines a modern fuel-station network with convenient food, mobility, parcel and digital services.", "Our offer evolves with the way you travel, shop and live — from high-quality fuels to rapid EV charging and one connected VITAY ecosystem."],
    features: [["Our fuel stations","The largest and most advanced network in the region, ready wherever your journey takes you."],["E-mobility","A fast-growing ORLEN Charge network makes electric travel simple and accessible."],["Offers for drivers","Fuel, services, rewards and everyday benefits created around drivers."],["Mobile applications","ORLEN VITAY, ORLEN Charge and mFLOTA keep your services close at hand."],["Beyond the station","Stop.Cafe, ORLEN Paczka and ORLEN w ruchu make every stop more useful."],["Customer service","Clear support and convenient contact whenever you need help."]],
    spotlight:{title:"Our fuel stations",text:"Make use of the wide offer of the biggest and the most advanced fuel stations network in Central and Eastern Europe. See for yourself that an ORLEN station is always nearby!",image:"assets/images/retail/orlen-station.jpg",cta:"Find a station",href:"fuel-stations.html"},
    sectionTitle:"You are always on the way with us", sectionText:"Our stations are more than places to refuel. They are modern service points where mobility, food, shopping and digital convenience meet.", image:"assets/images/retail/orlen-station.jpg",
    stats:[["3,500","fuel stations across 7 markets"],["15m+","customers in the region"],["2,600","non-fuel format points"],["3","connected mobile apps"]]
  },
  business: {
    title:"For business", eyebrow:"For business", lead:"Competitive delivery terms and a wide range of products and services", hero:"assets/images/what-we-do/refinery.jpg",
    introTitle:"A reliable partner for modern business", intro:["ORLEN offers refinery and petrochemical products, electrical energy and specialist services for companies operating across many industries.","An integrated supply chain and experience in international markets allow us to deliver securely, efficiently and at scale."],
    features:[["Fuels","Automotive, marine, aviation and heating fuels supported by international trade expertise."],["Petrochemicals","A broad portfolio of advanced products used in manufacturing and everyday life."],["Energy","Reliable energy products and solutions for organisations of every size."],["Fleet cards","Convenient tools and services that help companies manage mobility costs."],["Business applications","e-Hurt, e-Faktura, e-Kolej and self-service collection."],["Tenders and supplies","Transparent access to procurement and cooperation opportunities."]],
    sectionTitle:"Products that power growth", sectionText:"Our advanced products are available in more than 90 countries on six continents. We combine scale with a practical understanding of individual business needs.", image:"assets/images/what-we-do/refinery.jpg",
    stats:[["90+","countries served"],["6","continents"],["40","petrochemical products"],["30m+ t","annual crude throughput"]]
  },
  baltic: {
    title:"Baltic Power", eyebrow:"Offshore wind energy", lead:"The largest green energy project in Central Europe", hero:"assets/images/what-we-do/wind.jpg",
    introTitle:"Power from the Baltic Sea", intro:["Baltic Power is a joint venture between ORLEN and Northland Power and the most advanced offshore wind project in Poland.","The project combines global offshore experience with the strength of the Polish supply chain, creating a new foundation for the region’s energy security."],
    features:[["76 turbines","Modern 15 MW turbines will form the offshore wind farm."],["1.2 GW capacity","Clean electricity at a scale that changes the national energy mix."],["1.5 million homes","Enough renewable energy to cover the daily needs of around 1.5 million households."],["Polish Baltic Sea","The farm is being developed approximately 23 km north of the coastline."],["Lower emissions","Renewable generation will avoid millions of tonnes of CO₂ over its operating life."],["Regional investment","Ports, services and local suppliers participate in a landmark infrastructure project."]],
    sectionTitle:"Energy transformation in action", sectionText:"Offshore installation began in 2025. Baltic Power is not only a wind farm — it is a long-term investment in clean energy, industry and expertise for Central Europe.", image:"assets/images/what-we-do/wind.jpg",
    stats:[["1.2 GW","total capacity"],["76","wind turbines"],["15 MW","per turbine"],["~3%","of Poland’s electricity demand"]]
  },
  sustainability: {
    title:"Sustainability", eyebrow:"Sustainability", lead:"A responsible transition for people, business and the environment", hero:"assets/images/what-we-do/employees.png",
    introTitle:"We are changing energy in Central Europe", intro:["We develop in accordance with sustainable-development principles, reducing our impact on the climate and environment while supporting secure and affordable energy.","Our direction is clear: grow low- and zero-emission energy, transform existing assets responsibly and reach carbon neutrality by 2050."],
    features:[["Energy transition","Renewables, natural gas, SMR, hydrogen, CCUS and sustainable mobility."],["Sustainability strategy","Measurable goals that connect business transformation with social responsibility."],["Carbon footprint","A structured path for lowering emissions across operations and products."],["Climate governance","Clear responsibility, oversight and risk management throughout the Group."],["Reports and policies","Transparent information about progress, commitments and performance."],["Green finance","Financing tools that support projects with positive environmental impact."]],
    sectionTitle:"A just transition leaves no one behind", sectionText:"Employees, communities, customers, suppliers and business partners are central to the way ORLEN transforms. Responsible growth is built through dialogue and accountability.", image:"assets/images/what-we-do/employees.png",
    stats:[["2050","net-zero target"],["12.8 GW","planned RES capacity by 2035"],["-25%","Oil & Gas emissions by 2035"],["4 mt","CO₂ transport and storage capacity"]]
  },
  strategy: {
    title:"The energy of tomorrow starts today", eyebrow:"Strategy 2035", lead:"Secure energy supplies and a pragmatic transition for Central and Eastern Europe", hero:"assets/images/what-we-do/check-strategy.jpg",
    introTitle:"Driving force of Europe", intro:["Our energy drives change across the region. We balance robust demand for traditional energy sources with the accelerating shift towards decarbonisation.","By transforming assets, scaling renewable solutions and building an integrated offering, ORLEN is creating a resilient business prepared for the future."],
    features:[["Upstream & Supply","Up to 27 bcm of diversified natural gas delivered to the market annually."],["Downstream","More than 25% renewable energy in ORLEN fuels by 2035."],["Energy","12.8 GW of renewable capacity and 0.6 GW of SMR capacity."],["Consumers & Products","A connected ecosystem serving 10 million loyal VITAY users."],["Stable growth","An ambition to deliver long-term EBITDA growth and attractive dividends."],["Responsible investment","Disciplined investment focused on resilient, lower-emission growth."]],
    sectionTitle:"One integrated ORLEN ecosystem", sectionText:"Each business line complements the others. Digital integration and the transformation of traditional operations create a diversified model that is more resilient to market volatility.", image:"assets/images/what-we-do/check-strategy.jpg",
    stats:[["12.8 GW","renewable capacity"],["27 bcm","gas delivered annually"],["10m","VITAY users"],["PLN 350–380bn","planned CAPEX 2025–2035"]]
  },
  vision: {
    title:"Our vision", eyebrow:"About us", lead:"The energy of tomorrow starts today", hero:"assets/images/what-we-do/check-vision.jpg",
    introTitle:"Responsible and just transition", intro:["We are committed to delivering low- and zero-carbon energy at affordable prices, while meeting growing demand and ensuring energy security in the region.","People remain at the core of our transformation — our employees, local communities, business partners and consumers."],
    features:[["The future starts now","We increase efficiency and develop new business areas while transforming our core segments."],["New energy","Strong integrated companies can create efficient and sustainable technologies."],["Responsible growth","We minimise adverse impacts while using the opportunities of a low-carbon economy."],["Secure supply","A balanced portfolio helps protect customers and regional economies."],["Innovation","Modern mobility, energy and petrochemical solutions answer changing expectations."],["People first","A fair and inclusive transition is one that leaves no one behind."]],
    sectionTitle:"A modern multi-utility group", sectionText:"Sustainability is integral to ORLEN’s strategy. Our growth pillars are complemented by innovation in retail, mobility, energy and petrochemicals.", image:"assets/images/what-we-do/check-vision.jpg",
    stats:[["2035","strategy horizon"],["2050","carbon neutrality"],["4","strong business areas"],["1","integrated ecosystem"]]
  },
  poland:{title:"Polish operations",eyebrow:"Upstream at ORLEN",lead:"Exploration and production supporting Poland’s energy security",hero:"assets/images/what-we-do/upstream.jpg",introTitle:"A strong domestic asset base",intro:["ORLEN Upstream Poland develops hydrocarbon resources using modern geological, drilling and production expertise.","Domestic operations are an important part of a diversified supply portfolio and the long-term transformation of the ORLEN Group."],features:[["Exploration","Advanced geological analysis identifies promising domestic resources."],["Production","Safe and efficient production of natural gas and crude oil."],["Technology","Modern solutions improve recovery and lower operational impact."],["Expert teams","Integrated specialists manage projects from concept to production."],["Environment","Operations are planned with care for local communities and nature."],["Security","Polish production strengthens a resilient regional energy system."]],sectionTitle:"Knowledge rooted in Poland",sectionText:"Decades of upstream experience are combined with modern technology and rigorous safety standards.",image:"assets/images/what-we-do/upstream.jpg",stats:[["Poland","core market"],["60+ years","of experience"],["24/7","operational focus"],["1 goal","secure energy"]]},
  canada:{title:"Canadian operations",eyebrow:"Upstream at ORLEN",lead:"A diversified portfolio of high-quality upstream assets",hero:"assets/images/what-we-do/upstream.jpg",introTitle:"Building value in Western Canada",intro:["ORLEN Upstream Canada manages exploration and production assets in one of the world’s most established energy markets.","Local expertise, disciplined investment and responsible operations support the broader ORLEN upstream portfolio."],features:[["Asset portfolio","A balanced collection of producing and development assets."],["Operations","Efficient field management supported by experienced local teams."],["Technology","Data-led development and modern production methods."],["Safety","Strong standards protect employees, contractors and communities."],["Stewardship","Responsible land and water management throughout the asset lifecycle."],["Integration","Canadian output complements ORLEN’s European supply base."]],sectionTitle:"International expertise, local responsibility",sectionText:"Operations are developed with respect for Canadian regulations, partners, communities and the environment.",image:"assets/images/what-we-do/upstream.jpg",stats:[["Canada","operating region"],["Integrated","asset management"],["Safe","field operations"],["Long-term","value creation"]]},
  norway:{title:"Norwegian operations",eyebrow:"Upstream at ORLEN",lead:"Natural gas from the Norwegian Continental Shelf",hero:"assets/images/what-we-do/wind.jpg",introTitle:"A strategic source for Central Europe",intro:["Norway is a cornerstone of ORLEN’s diversified natural-gas portfolio and a major contributor to regional energy security.","Production assets on the Norwegian Continental Shelf connect to European markets through robust infrastructure."],features:[["Continental Shelf","A portfolio of producing fields and development projects."],["Natural gas","Reliable volumes support customers across Central Europe."],["Partnerships","Projects are developed with experienced international operators."],["Technology","Offshore expertise improves safety and asset performance."],["Lower intensity","Modern fields support a more efficient transition fuel supply."],["Security","Diversified Norwegian production strengthens resilience."]],sectionTitle:"Energy delivered through cooperation",sectionText:"ORLEN’s Norwegian business combines strong partnerships, offshore expertise and long-term investment.",image:"assets/images/what-we-do/wind.jpg",stats:[["Norway","strategic market"],["Offshore","production"],["Europe","connected supply"],["2035","growth horizon"]]},
  libya:{title:"Libyan operations",eyebrow:"Upstream at ORLEN",lead:"International exploration backed by ORLEN expertise",hero:"assets/images/what-we-do/upstream.jpg",introTitle:"Exploration in North Africa",intro:["ORLEN’s Libyan activities form part of a geographically diversified exploration portfolio.","Projects are managed with careful attention to operating conditions, safety, partnerships and long-term value."],features:[["Exploration","Geological and seismic work evaluates prospective resources."],["Partnership","Cooperation with local institutions and industry partners."],["Expertise","International teams contribute technical and commercial knowledge."],["Safety","Risk-aware planning is fundamental to every activity."],["Responsibility","Projects respect communities, regulations and the environment."],["Portfolio","North African opportunities complement other upstream regions."]],sectionTitle:"A disciplined international approach",sectionText:"Every project is assessed against technical, economic, environmental and security requirements.",image:"assets/images/what-we-do/upstream.jpg",stats:[["Libya","operating region"],["Upstream","exploration"],["Global","expertise"],["Safety","first priority"]]},
  exalo:{title:"Exalo Drilling",eyebrow:"Upstream services",lead:"Specialist drilling services for the oil and gas sector",hero:"assets/images/what-we-do/refinery.jpg",introTitle:"From planning to the well site",intro:["Exalo Drilling provides drilling, workover and specialist well services supported by experienced crews and technical facilities.","The company’s capabilities serve upstream projects in Poland and international markets."],features:[["Drilling","Integrated execution of complex drilling programmes."],["Workover","Services that maintain and improve producing wells."],["Equipment","Specialist rigs and technical infrastructure."],["Engineering","Planning and expert support across project stages."],["Safety culture","Processes focused on people, assets and the environment."],["International reach","Experience delivered across varied geological conditions."]],sectionTitle:"Experience below the surface",sectionText:"Technical competence and dependable project delivery make drilling operations safer and more efficient.",image:"assets/images/what-we-do/refinery.jpg",stats:[["Drilling","core service"],["Workover","well support"],["Expert","field crews"],["Global","project capability"]]},
  pakistan:{title:"Pakistan operations",eyebrow:"Upstream at ORLEN",lead:"Developing natural-gas resources with local expertise",hero:"assets/images/what-we-do/upstream.jpg",introTitle:"Production and exploration in Pakistan",intro:["ORLEN’s Pakistan operations combine producing assets with continued exploration and development activity.","Natural-gas projects contribute to local supply while expanding the Group’s international upstream experience."],features:[["Natural gas","Production supports the needs of the domestic market."],["Exploration","New prospects are evaluated through geological and seismic work."],["Development","Discoveries progress through disciplined project planning."],["Local teams","Experienced professionals lead day-to-day operations."],["Community","Engagement supports responsible and lasting cooperation."],["Safety","High standards guide every field activity."]],sectionTitle:"Growing through partnership",sectionText:"Close cooperation with local stakeholders is essential to safe, responsible and efficient operations.",image:"assets/images/what-we-do/upstream.jpg",stats:[["Pakistan","operating region"],["Gas","primary product"],["Local","expert teams"],["Long-term","development"]]},
  geofizyka:{title:"Geofizyka Toruń",eyebrow:"Upstream services",lead:"Geophysical solutions that reveal what lies beneath",hero:"assets/images/what-we-do/upstream.jpg",introTitle:"Data for better exploration decisions",intro:["Geofizyka Toruń delivers seismic acquisition, processing and interpretation services for the energy and natural-resources sectors.","Advanced technology and experienced specialists turn subsurface data into actionable geological understanding."],features:[["Seismic acquisition","Onshore field surveys adapted to varied terrain."],["Data processing","High-performance workflows transform raw measurements."],["Interpretation","Experts create reliable subsurface models."],["Technology","Modern equipment supports precision and efficiency."],["International projects","Teams operate in demanding environments worldwide."],["Integrated service","Support extends from survey design to final insight."]],sectionTitle:"See more. Understand more.",sectionText:"High-quality geophysical data reduces uncertainty and helps clients make responsible investment decisions.",image:"assets/images/what-we-do/upstream.jpg",stats:[["Seismic","core expertise"],["3D","subsurface insight"],["Global","field experience"],["Data-led","decisions"]]},
  anwil:{title:"ANWIL",eyebrow:"ORLEN Group",lead:"A leading producer of fertilizers and chemical products",hero:"assets/images/business/petrochemicals.jpeg",introTitle:"Chemistry supporting modern industry",intro:["ANWIL combines large-scale industrial production with specialist knowledge in nitrogen fertilizers and plastics.","The company develops its facilities responsibly, focusing on product quality, operational safety and improved environmental performance."],features:[["Nitrogen fertilizers","Products supporting efficient agricultural production."],["PVC and chemicals","Materials used across construction, manufacturing and infrastructure."],["Quality","Consistent standards backed by laboratory and process control."],["Modernisation","Investment strengthens efficiency and production capability."],["Safety","Responsible operations protect people and neighbouring communities."],["ORLEN integration","Shared expertise and scale create lasting industrial value."]],sectionTitle:"Industry built on expertise",sectionText:"Advanced production, logistics and technical competence help ANWIL serve customers in Poland and international markets.",image:"assets/images/business/petrochemicals.jpeg",stats:[["Chemicals","core business"],["Poland","production base"],["Modern","industrial assets"],["Responsible","development"]]},
  energa:{title:"Grupa Energa",eyebrow:"ORLEN Group",lead:"Energy distribution, generation and services for customers",hero:"assets/images/business/energy.jpeg",introTitle:"Powering homes, companies and communities",intro:["Grupa Energa is an important part of Poland's electricity system, combining distribution infrastructure, generation assets and customer services.","Its capabilities support security of supply and the transformation toward a smarter, lower-emission energy system."],features:[["Distribution","A broad electricity network connects customers and regions."],["Renewables","Wind, hydro and solar assets expand cleaner generation."],["Customers","Energy products and services for households and business."],["Grid investment","Modern infrastructure supports resilience and new connections."],["Digital solutions","Technology improves service and network management."],["Transition","New capacity supports ORLEN's integrated energy strategy."]],sectionTitle:"A modern electricity system",sectionText:"Network investment and renewable generation are essential foundations for an affordable and secure transition.",image:"assets/images/sustainability/energy-transition.jpeg",stats:[["Energy","core sector"],["Grid","strategic asset"],["Renewables","growing portfolio"],["Millions","of customers"]]},
  deutschland:{title:"ORLEN Deutschland",eyebrow:"ORLEN Group",lead:"Convenient mobility and retail services in the German market",hero:"assets/images/retail/orlen-station.jpg",introTitle:"A strong retail network in Germany",intro:["ORLEN Deutschland serves drivers through a modern network of fuel stations and convenience services.","Customer-focused formats combine fuels, food, shopping and mobility solutions adapted to the German market."],features:[["Fuel stations","A well-established network in a major European market."],["Mobility","Products and services for changing transport needs."],["Convenience","Retail formats designed around everyday journeys."],["Quality fuels","Reliable products supported by the wider ORLEN supply chain."],["Customer experience","Simple, accessible service across the station network."],["Development","Modernisation prepares locations for future mobility."]],sectionTitle:"Always close to the customer",sectionText:"The German retail business combines local market knowledge with the scale and experience of the ORLEN Group.",image:"assets/images/retail/orlen-station.jpg",stats:[["Germany","core market"],["Retail","customer focus"],["Mobility","integrated offer"],["Every day","reliable service"]]},
  baltics:{title:"ORLEN Baltics Retail",eyebrow:"ORLEN Group",lead:"Mobility services for customers across the Baltic region",hero:"assets/images/retail/driving.jpeg",introTitle:"A regional retail presence",intro:["ORLEN's Baltic retail activities connect fuel, convenience and mobility services with a supply network serving the region.","Local teams adapt the offer to customer needs while benefiting from the capabilities of an integrated energy group."],features:[["Regional network","Stations support journeys across Baltic markets."],["Retail services","Food, shopping and convenience complement the fuel offer."],["Supply security","Integrated logistics help maintain dependable availability."],["Customer focus","Services evolve with local expectations."],["Mobility transition","Locations are prepared for changing transport technologies."],["Group strength","Shared systems and expertise support efficient growth."]],sectionTitle:"Connected across the Baltics",sectionText:"A customer-focused network brings dependable energy and useful everyday services closer to drivers.",image:"assets/images/retail/driving.jpeg",stats:[["Baltics","regional reach"],["Stations","retail network"],["Integrated","supply"],["Growing","mobility services"]]},
  paliwa:{title:"ORLEN Paliwa",eyebrow:"ORLEN Group",lead:"Fuel supply and energy solutions for business customers",hero:"assets/images/fuels/company.jpeg",introTitle:"A dependable wholesale partner",intro:["ORLEN Paliwa supplies a broad portfolio of fuel and energy products to companies throughout Poland.","Specialist sales, logistics and customer-service teams support secure deliveries tailored to different industries."],features:[["Wholesale fuels","A comprehensive product portfolio for business."],["Logistics","Coordinated deliveries and dependable availability."],["LPG","Solutions for commercial, industrial and household needs."],["Fuel oil","Products matched to heating and production requirements."],["Customer service","Dedicated support for long-term cooperation."],["ORLEN supply","Integrated capabilities strengthen security and quality."]],sectionTitle:"Energy delivered to business",sectionText:"Scale, logistics and product expertise make ORLEN Paliwa a reliable partner for customers with demanding supply needs.",image:"assets/images/business/fuels.jpeg",stats:[["Poland","nationwide reach"],["Fuels","broad portfolio"],["Business","dedicated service"],["Reliable","delivery"]]},
  petrobaltic:{title:"ORLEN Petrobaltic",eyebrow:"ORLEN Group",lead:"Offshore exploration and production in the Baltic Sea",hero:"assets/images/what-we-do/upstream.jpg",introTitle:"Experience on the Polish Baltic shelf",intro:["ORLEN Petrobaltic develops offshore hydrocarbon resources and specialist marine capabilities in the Baltic Sea.","Its knowledge supports domestic production, responsible field management and the broader transformation of offshore energy."],features:[["Offshore production","Safe operation of Baltic Sea assets."],["Exploration","Geological expertise identifies resource potential."],["Marine logistics","Specialist vessels and teams support offshore work."],["Field management","Assets are operated across their complete lifecycle."],["Environment","Marine operations follow rigorous protection standards."],["Energy security","Domestic resources add resilience to the supply portfolio."]],sectionTitle:"Knowledge shaped by the Baltic Sea",sectionText:"Decades of offshore experience bring together engineering, geology, logistics and environmental responsibility.",image:"assets/investors/news-baltic-first-power.jpeg",stats:[["Baltic Sea","operating area"],["Offshore","specialist expertise"],["Poland","domestic production"],["Safety","daily priority"]]},
  unipetrol:{title:"ORLEN Unipetrol",eyebrow:"ORLEN Group",lead:"An integrated refining and petrochemical business in Czechia",hero:"assets/images/what-we-do/refinery.jpg",introTitle:"Energy and materials for the Czech market",intro:["ORLEN Unipetrol connects refining, petrochemicals and retail in one of Central Europe's key industrial markets.","Its integrated model serves transport, manufacturing and consumers while progressing toward lower-emission operations."],features:[["Refining","Modern assets produce fuels and other essential products."],["Petrochemicals","Materials support a wide range of industries."],["Retail","A strong station network serves drivers across Czechia."],["Research","Innovation improves products and processes."],["Circularity","New approaches reduce resource use and environmental impact."],["Transformation","Investment prepares industrial assets for the future."]],sectionTitle:"An integrated Czech energy company",sectionText:"From industrial production to customer-facing retail, ORLEN Unipetrol creates value across a connected supply chain.",image:"assets/images/business/petrochemicals.jpeg",stats:[["Czechia","core market"],["Integrated","business model"],["Industry","and retail"],["Future","focused investment"]]}
};

const p = pages[pageKey] || pages.retail;
const operationPages = [
  ["poland", "Polish operations", "upstream-poland.html"],
  ["canada", "Canadian operations", "upstream-canada.html"],
  ["norway", "Norwegian operations", "upstream-norway.html"],
  ["libya", "Libyan operations", "upstream-libya.html"],
  ["exalo", "Exalo Drilling", "exalo-drilling.html"],
  ["pakistan", "Pakistan operations", "upstream-pakistan.html"],
  ["geofizyka", "Geofizyka Toruń", "geofizyka-torun.html"]
];

const operationDetails = {
  poland: { area: "Exploration and production", region: "Poland", email: "" },
  canada: { area: "Exploration and production", region: "Canada", email: "" },
  norway: { area: "Offshore exploration and production", region: "Norway", email: "" },
  libya: { area: "International exploration", region: "Libya", email: "" },
  exalo: { area: "Drilling and well services", region: "Poland and international markets", email: "" },
  pakistan: { area: "Natural gas exploration and production", region: "Pakistan", email: "" },
  geofizyka: { area: "Geophysical services", region: "Poland and international markets", email: "" }
};

const currentOperation = operationDetails[pageKey];
const operationContactMarkup = currentOperation ? `
 <section class="operation-contact" aria-labelledby="operation-contact-title">
  <div class="page-width">
   <div class="operation-contact__head reveal">
    <div><p class="operation-contact__kicker">Contact</p><h2 id="operation-contact-title">Contact ${p.title}</h2></div>
    <p>Looking for information about this part of ORLEN's operations? The dedicated email contact will appear here once the local contact details are confirmed.</p>
   </div>
   <div class="operation-contact__grid">
    <article class="operation-contact__card reveal"><small>Email contact</small>${currentOperation.email ? `<a href="mailto:${currentOperation.email}">${currentOperation.email}</a>` : `<strong data-operation-email>Email address coming soon</strong>`}<span>This field is ready for the email address you provide.</span></article>
    <article class="operation-contact__card reveal"><small>Business profile</small><strong>${currentOperation.area}</strong><span>${currentOperation.region}</span></article>
   </div>
   <div class="operation-network">
    <h3>Explore our operations</h3>
    <nav class="operation-network__grid" aria-label="ORLEN operation pages">${operationPages.map(([key, name, href]) => `<a href="${href}"${key === pageKey ? ` aria-current="page"` : ""}>${name}</a>`).join("")}</nav>
   </div>
  </div>
 </section>` : "";
document.title = `${p.title} | ORLEN`;
const featureMarkup = p.features.map((f,i)=>`<article class="feature-card reveal"><span class="feature-card__number">${String(i+1).padStart(2,"0")}</span><h3>${f[0]}</h3><p>${f[1]}</p></article>`).join("");
const statsMarkup = p.stats.map(s=>`<div class="stat"><strong>${s[0]}</strong><span>${s[1]}</span></div>`).join("");
const spotlightMarkup = p.spotlight ? `<section class="retail-station page-width reveal"><div class="retail-station__image"><img src="${p.spotlight.image}" alt="Modern ORLEN fuel station"></div><div class="retail-station__copy"><p class="eyebrow">For you</p><h2>${p.spotlight.title}</h2><p>${p.spotlight.text}</p><a class="retail-station__cta" href="${p.spotlight.href}">${p.spotlight.cta} <span aria-hidden="true">→</span></a></div></section>` : "";
const retailPageMarkup = pageKey === "retail" ? `
<section class="retail-alternating page-width">
  <article class="retail-offer-row reveal"><div class="retail-offer-copy"><p class="retail-label">For you</p><h2>E-mobility</h2><p>Charge your car in a quick and convenient way, whenever you need it. Make use of our dynamically developing charging network.</p><div class="retail-actions"><a href="e-mobility.html">Find out more <span>→</span></a><a href="fuel-stations.html#electric-car-chargers">Find an EV-charger <span>→</span></a></div></div><div class="retail-offer-image"><img src="assets/images/retail/charging.jpeg" alt="Electric car charging at an ORLEN charging point"></div></article>
  <article class="retail-offer-row retail-offer-row--reverse reveal" id="offers-for-drivers"><div class="retail-offer-copy"><p class="retail-label">For drivers</p><h2>Our offer for drivers</h2><p>ORLEN is beyond the fuel. The company provides a variety of products and services which guarantee full comfort throughout your journey.</p><div class="retail-actions"><a href="#" data-local-only="true" target="_blank" rel="noreferrer">See more <span>→</span></a></div></div><div class="retail-offer-image"><img src="assets/images/retail/driving.jpeg" alt="Driver inside a modern car"></div></article>
</section>
<section class="retail-apps" id="mobile-apps"><div class="page-width"><h2>Explore our mobile apps</h2><div class="retail-app-grid">
  <article class="retail-app-card reveal"><a class="retail-card-image" href="e-mobility.html"><img src="assets/images/retail/app-orlen-charge.jpeg" alt="ORLEN Charge mobile application"></a><div class="retail-card-copy"><p class="retail-label">Apps</p><h3>ORLEN Charge</h3><p>ORLEN Charge app lets you find the closest EV charging point with ease, check its parameters and availability or contact our 24/7 helpline.</p><a href="e-mobility.html">Find out more <span>→</span></a></div></article>
  <article class="retail-app-card reveal"><a class="retail-card-image" href="#" data-local-only="true" target="_blank" rel="noreferrer"><img src="assets/images/retail/app-orlen-vitay.jpeg" alt="ORLEN VITAY mobile application"></a><div class="retail-card-copy"><p class="retail-label">Apps</p><h3>ORLEN VITAY</h3><p>All the possibilities provided by the VITAY card can be found through our mobile app. Find stations, collect points and receive coupons and discounts.</p><a href="#" data-local-only="true" target="_blank" rel="noreferrer">Find out more <span>→</span></a></div></article>
  <article class="retail-app-card reveal"><a class="retail-card-image" href="#" data-local-only="true" target="_blank" rel="noreferrer"><img src="assets/images/retail/app-mflota.jpeg" alt="mFLOTA mobile application"></a><div class="retail-card-copy"><p class="retail-label">Apps</p><h3>mFLOTA</h3><p>mFLOTA supports FLOTA, OPEN DRIVE and MIKROFLOTA users and enables convenient payment for fleet transactions directly by the fuel pump.</p><a href="#" data-local-only="true" target="_blank" rel="noreferrer">Find out more <span>→</span></a></div></article>
</div></div></section>
<section class="retail-beyond page-width"><h2>Beyond the station</h2><article class="retail-stop-cafe reveal"><div class="retail-stop-image"><img src="assets/images/retail/stop-cafe.jpeg" alt="Burger and hot dog from the ORLEN Stop.Cafe offer"></div><div class="retail-stop-copy"><p class="retail-label">For you</p><h3>ORLEN Stop.Cafe offer</h3><p>Take a break for coffee and a fresh and tasty meal at one of more than 2000 ORLEN Stop.Cafe points.</p><a href="stop-cafe.html">Find out more <span>→</span></a></div></article><div class="retail-beyond-grid">
  <article class="retail-image-card reveal"><a href="orlen-w-ruchu.html"><img src="assets/images/retail/orlen-w-ruchu.jpeg" alt="ORLEN w ruchu retail point"><div><p class="retail-label">For you</p><h3>ORLEN w ruchu</h3><span>See more →</span></div></a></article>
  <article class="retail-image-card reveal"><a href="orlen-paczka.html"><img src="assets/images/retail/orlen-paczka.jpeg" alt="Woman using an ORLEN Paczka parcel locker"><div><p class="retail-label">For you</p><h3>ORLEN Paczka</h3><span>See more →</span></div></a></article>
</div></section>
<section class="retail-fleet reveal"><img src="assets/images/retail/orlen-flota.jpeg" alt="ORLEN FLOTA business services"><div class="retail-banner-shade"></div><div class="retail-fleet-copy page-width"><p>Our fleet offer</p><h2>Do you run a business?</h2><div>We prepared something for you! Our offer provides solutions tailored to you and your company’s needs. Take advantage of quick and secure transactions in Poland and abroad, discounts, simplified invoicing and deferred payment dates.</div><a href="business-offer.html">Find out more <span>→</span></a></div></section>
<section class="retail-campaign page-width"><article class="retail-campaign-card reveal"><div class="retail-campaign-copy"><p class="retail-label">Campaign</p><h2>#DobryKierowca campaign</h2><p>Even the smallest actions can benefit the people around us. Join the campaign and help us raise road safety in Poland. We can power a better future together!</p><a href="#" data-local-only="true" target="_blank" rel="noreferrer">Find out more <span>→</span></a></div><div class="retail-campaign-image"><img src="assets/images/retail/good-driver.jpeg" alt="The Good Driver road safety campaign"></div></article></section>
<section class="retail-family"><div class="page-width retail-family-grid"><div class="retail-family-copy"><p class="retail-label">For you</p><h2>The Large Family Card</h2><p>Large families can rely on us. With all our hearts! We prepared a special offer for owners of the Nationwide Large Family Card.</p><ul><li><strong>8 gr discount</strong> per litre of standard fuels</li><li><strong>10 gr discount</strong> per litre of VERVA fuels</li><li><strong>20% discount</strong> on all Stop.Cafe products</li><li><strong>20% discount</strong> on car washing</li></ul><p>The Large Family Card is accepted at all ORLEN fuel stations.</p></div><div class="retail-family-image"><img src="assets/images/retail/large-family-card.jpeg" alt="ORLEN Large Family Card"></div></div></section>
<section class="retail-contact page-width"><h2>Contact</h2><div class="retail-contact-grid"><div class="retail-phone"><a href="tel:+447378347853">+44 7378347853</a><span>For landline phones</span></div><div class="retail-phone"><a href="tel:+447378347853">+44 7378347853</a><span>For mobile phones</span></div><article class="retail-contact-card"><img src="assets/images/retail/contact.jpeg" alt="ORLEN customer service"><div><p class="retail-label">Contact</p><h3>Customer service</h3><p>Any questions? We are at your service.</p><a href="report-question-or-complaint.html">Contact us <span>→</span></a></div></article></div></section>
` : "";
const accordionMarkup = p.features.slice(0,4).map((f,i)=>`<div class="accordion-item"><button class="accordion-trigger" type="button" aria-expanded="${i===0}"><span>${f[0]}</span><span aria-hidden="true">+</span></button><div class="accordion-panel"><div><p>${f[1]} ORLEN combines specialist knowledge, responsible operations and solutions designed for lasting value.</p></div></div>`).join("");

document.body.innerHTML = `
<a class="skip-link" href="#main-content">Skip to content</a>
<header class="site-header" id="site-header"><div class="header-shell">
 <a class="brand" href="index.html" aria-label="ORLEN homepage"><img class="brand-overlay" src="assets/images/orlen-logo-white.png" alt="ORLEN"><img class="brand-solid" src="assets/images/orlen-logo-alt.jpg" alt="" aria-hidden="true"></a>
 <nav class="utility-nav" aria-label="Utility navigation"><button class="utility-button" type="button" data-panel-open="group-panel"><span>ORLEN Group</span></button><a href="report-question-or-complaint.html"><span>Contact</span></a><button class="utility-button language-trigger" type="button" aria-expanded="false" aria-controls="language-menu"><span>English</span><span>⌄</span></button><div class="language-menu" id="language-menu" hidden><a href="#" data-language="pl">Polski</a><a class="active" href="#" data-language="en" aria-current="page">English</a></div></nav>
 <nav class="primary-nav" aria-label="Primary navigation"><a class="active" href="what-we-do.html">About Us</a><a href="retail-offer.html">For you</a><a href="business-offer.html">For business</a><a href="sustainability.html">Sustainability</a><a href="investor-relations.html">Investor relations</a><a href="career.html">Career</a></nav>
 <div class="header-actions"><button class="icon-button search-trigger" type="button" aria-label="Open search" data-panel-open="search-panel"><svg aria-hidden="true" viewBox="0 0 24 24"><circle cx="11" cy="11" r="6.5"/><path d="m16 16 4.3 4.3"/></svg></button><button class="icon-button menu-trigger" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="mobile-menu"><span></span><span></span><span></span></button></div>
</div></header>
<div class="mobile-menu" id="mobile-menu" aria-hidden="true"><nav><a href="what-we-do.html"><span>About Us</span><span>→</span></a><a href="retail-offer.html"><span>For you</span><span>→</span></a><a href="business-offer.html"><span>For business</span><span>→</span></a><a href="sustainability.html"><span>Sustainability</span><span>→</span></a><a href="investor-relations.html"><span>Investor relations</span><span>→</span></a><a href="career.html"><span>Career</span><span>→</span></a></nav><div class="mobile-utility"><button type="button" data-panel-open="group-panel">ORLEN Group</button><a href="report-question-or-complaint.html">Contact</a><a href="#" data-language-toggle data-language="pl">Polski</a></div></div>
<aside class="side-panel" id="group-panel" aria-hidden="true"><button class="panel-close" type="button" aria-label="Close" data-panel-close>×</button><p class="eyebrow">Companies</p><h2>ORLEN Group</h2><div class="group-links"><a href="anwil.html">ANWIL</a><a href="baltic-power.html">Baltic Power</a><a href="exalo-drilling.html">Exalo Drilling</a><a href="geofizyka-torun.html">Geofizyka Toruń</a><a href="grupa-energa.html">Grupa Energa</a><a href="orlen-baltics-retail.html">ORLEN Baltics Retail</a><a href="orlen-deutschland.html">ORLEN Deutschland</a><a href="orlen-paliwa.html">ORLEN Paliwa</a><a href="orlen-petrobaltic.html">ORLEN Petrobaltic</a><a href="orlen-unipetrol.html">ORLEN Unipetrol</a><a href="upstream-canada.html">ORLEN Upstream Canada</a><a href="upstream-norway.html">ORLEN Upstream Norway</a><a href="upstream-poland.html">ORLEN Upstream Poland</a></div></aside>
<section class="search-panel" id="search-panel" aria-hidden="true"><button class="panel-close" type="button" aria-label="Close" data-panel-close>×</button><div class="search-inner"><p class="eyebrow">Search ORLEN</p><h2 id="search-title">What are you looking for?</h2><form class="search-form" id="search-form"><input id="site-search" name="q" type="search" placeholder="Search"><button type="submit" aria-label="Submit search">→</button></form><p class="search-message" id="search-message" aria-live="polite"></p><div class="quick-links"><span>Shortcuts</span><a href="retail-offer.html">Retail offer</a><a href="business-offer.html">Business offer</a><a href="strategy-2035.html">Strategy 2035</a></div></div></section><div class="panel-backdrop" aria-hidden="true"></div>
<main id="main-content">
 <section class="detail-hero"><img src="${p.hero}" alt=""><div class="detail-hero__content page-width"><p class="eyebrow">${p.eyebrow}</p><h1>${p.title}</h1><p>${p.lead}</p></div></section>
 <section class="detail-intro page-width reveal"><div class="kicker">ORLEN Group</div><div><h2>${p.introTitle}</h2>${p.intro.map(x=>`<p>${x}</p>`).join("")}</div></section>
 ${spotlightMarkup}
 ${retailPageMarkup}
 <section class="feature-band"><div class="page-width"><div class="feature-band__heading"><h2>Explore our activities</h2><p>Discover the solutions, capabilities and commitments that shape this part of the ORLEN Group.</p></div><div class="feature-grid">${featureMarkup}</div></div></section>
 <section class="detail-section page-width"><div class="detail-split reverse reveal"><div class="detail-split__media"><img src="${p.image}" alt=""></div><div class="detail-split__copy"><h2>${p.sectionTitle}</h2><p>${p.sectionText}</p><a class="detail-link" href="#details">Find out more <span>→</span></a></div></div></section>
 <section class="stats-band"><div class="page-width stats-grid">${statsMarkup}</div></section>
 <section class="accordion-section" id="details"><div class="page-width"><h2>Find out more</h2><div class="detail-accordion">${accordionMarkup}</div></div></section>
 ${operationContactMarkup}
 <section class="related-pages"><div class="page-width"><h2>See also</h2><div class="related-grid"><a class="related-card" href="what-we-do.html"><small>About us</small><strong>What we do</strong><span>→</span></a><a class="related-card" href="strategy-2035.html"><small>About us</small><strong>Strategy 2035</strong><span>→</span></a><a class="related-card" href="our-vision.html"><small>About us</small><strong>Our vision</strong><span>→</span></a></div></div></section>
</main>
<footer class="site-footer" id="site-footer"><div class="footer-main page-width"><div class="footer-brand"><img src="assets/images/orlen-logo-alt.jpg" alt="ORLEN"><p>Copyright © 1996-2025<br>All rights reserved</p></div><div class="footer-column"><button class="footer-heading" type="button" aria-expanded="true">Shortcuts <span>+</span></button><div class="footer-links"><a href="business-offer.html">For business</a><a href="tenders-and-supplies.html">Tenders and supplies</a><a href="fuel-stations.html">Fuel stations</a><a href="vitay-program.html">VITAY Program</a></div></div><div class="footer-column"><button class="footer-heading" type="button" aria-expanded="true">About the company <span>+</span></button><div class="footer-links"><a href="our-vision.html">Our vision</a><a href="press-pack.html">Press-pack</a><a href="report-question-or-complaint.html">Report a question or complaint</a></div></div><nav class="footer-social" aria-label="Social media"><a href="#" aria-disabled="true" tabindex="-1" aria-label="Facebook">f</a><a href="#" aria-disabled="true" tabindex="-1" aria-label="LinkedIn">in</a><a href="#" aria-disabled="true" tabindex="-1" aria-label="X">X</a><a href="#" aria-disabled="true" tabindex="-1" aria-label="YouTube">▶</a><a href="#" aria-disabled="true" tabindex="-1" aria-label="TikTok">♪</a></nav></div><div class="footer-bottom page-width"><a href="site-information.html#sitemap">Sitemap</a><a href="site-information.html#privacy-policy">Privacy policy</a><a href="site-information.html#legal-disclaimer">Legal disclaimer</a><a href="site-information.html#personal-data">Personal data</a><a class="back-to-top" href="#main-content">Back to top ↑</a></div></footer>`;

document.querySelectorAll('.accordion-trigger').forEach(btn=>btn.addEventListener('click',()=>btn.setAttribute('aria-expanded',btn.getAttribute('aria-expanded')!=='true')));
document.querySelectorAll('a[href="#"]').forEach(a=>a.addEventListener('click',e=>e.preventDefault()));
